server:
  port: 3000

  spring:
   datasource:
     url: jdbc:mysql://localhost:3306/new_schema?useSSL=false&serverTimezone=UTC
     username: root
     password: 1234
   jpa:
     hibernate.ddl-auto: validate # Never use "update" in production!
     hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
     show-sql: true
     properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

     h2:
       console:
         enabled: true                  # Enable the console
         path: /h2-console             # Access path (default)
         settings:
           trace: false                # Disable trace output
           web-allow-others: false     # Disable remote access (security)